package View.Programming;

import javax.swing.JOptionPane;

import View.Home.JPanelMenu;

public class JInternalProgramming extends javax.swing.JInternalFrame {

    private JPanelNewProgramming programming;
    
    
    public JInternalProgramming() {
        initComponents();
        this.programming = new JPanelNewProgramming();
        showPanel();
        initNewComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Barra = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel_lista = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(1320, 738));
        setPreferredSize(new java.awt.Dimension(1320, 738));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Fondo.setMinimumSize(new java.awt.Dimension(1320, 710));
        jPanel_Fondo.setPreferredSize(new java.awt.Dimension(1320, 710));
        jPanel_Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("PROGRAMCIÓN DE VIAJES");
        jPanel_Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 290, 50));

        jPanel_Barra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel_Barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jToggleButton1.setText("NUEVA PROGRAMACIÓN");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel_Barra.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 340, 40));

        jPanel_Fondo.add(jPanel_Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 1200, 40));

        jPanel_lista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Prgramacion de Buses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N
        jPanel_lista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "UNIDAD BUS", "ORIGEN", "DESTINO", "FECHA", "HORA", "COSTO TOTAL", "ESTADO"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel_lista.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 760, 280));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Eliminar");
        jPanel_lista.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Editar");
        jPanel_lista.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Buscar por:");
        jPanel_lista.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel_lista.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 170, -1));

        jPanel_Fondo.add(jPanel_lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 800, 520));

        getContentPane().add(jPanel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        programming.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    //  ==========================================================
    //  INTERAACION DE LAS NUEVAS COMPONNETES DE PARA EL JINTERNAL
    //  ==========================================================
    private void showPanel(){
        jPanel_Fondo.add(programming, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130));
        programming.setVisible(false);
    }

    private void initNewComponents(){
        clickAdd ();
        clickCancel();
    }

    private void clickAdd (){
        JPanelNewProgramming.jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter()  {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                Object[] options = {"Si, proceder","No, Cancelar"};
                int confirmacion = JOptionPane.showOptionDialog(null, "¿Desea confirmar?", "Confirmación", JOptionPane.NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                // Procesar la opción seleccionada por el usuario
                if (confirmacion == JOptionPane.YES_OPTION) {
                    System.out.println("Confirmó");
                } else if (confirmacion == JOptionPane.NO_OPTION) {
                    System.out.println("No confirmó");
                } else if (confirmacion == JOptionPane.CLOSED_OPTION) {
                    System.out.println("Cerró el diálogo sin seleccionar ninguna opción");
                }
            }
        });
    }

    private void clickCancel (){
        JPanelNewProgramming.jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter()  {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                programming.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_Barra;
    private javax.swing.JPanel jPanel_Fondo;
    private javax.swing.JPanel jPanel_lista;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
