package View.Home;

public class JPanelMenu extends javax.swing.JPanel {

    public JPanelMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHome = new javax.swing.JLabel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelInformation = new javax.swing.JLabel();
        jLabelTicket = new javax.swing.JLabel();
        jLabelReport = new javax.swing.JLabel();
        jLabelProgramming = new javax.swing.JLabel();
        jLabelBuses = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelUsers = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 62, 80));
        setPreferredSize(new java.awt.Dimension(230, 740));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/Icons/menu.png"))); // NOI18N
        jLabelHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabelHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabelNombreUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/Icons/user.png"))); // NOI18N
        jLabelNombreUsuario.setText("Usuario");
        add(jLabelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 230, 120));

        jLabelInformation.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelInformation.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInformation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/Icons/info.png"))); // NOI18N
        jLabelInformation.setText("Información");
        jLabelInformation.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabelInformation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInformation.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelInformation.setIconTextGap(15);
        add(jLabelInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 230, 50));

        jLabelTicket.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTicket.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTicket.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/Icons/ticket.png"))); // NOI18N
        jLabelTicket.setText("Venta de pasajes");
        jLabelTicket.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabelTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTicket.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelTicket.setIconTextGap(15);
        add(jLabelTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, 50));

        jLabelReport.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelReport.setForeground(new java.awt.Color(204, 204, 204));
        jLabelReport.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/Icons/report.png"))); // NOI18N
        jLabelReport.setText("Reportes");
        jLabelReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabelReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelReport.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelReport.setIconTextGap(15);
        add(jLabelReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 230, 50));

        jLabelProgramming.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelProgramming.setForeground(new java.awt.Color(204, 204, 204));
        jLabelProgramming.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelProgramming.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/Icons/calendar.png"))); // NOI18N
        jLabelProgramming.setText("Programación");
        jLabelProgramming.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabelProgramming.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelProgramming.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelProgramming.setIconTextGap(15);
        add(jLabelProgramming, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 50));

        jLabelBuses.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelBuses.setForeground(new java.awt.Color(204, 204, 204));
        jLabelBuses.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBuses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/Icons/bus.png"))); // NOI18N
        jLabelBuses.setText("Buses");
        jLabelBuses.setToolTipText("");
        jLabelBuses.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabelBuses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelBuses.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelBuses.setIconTextGap(15);
        add(jLabelBuses, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, 50));

        jLabelInicio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelInicio.setForeground(new java.awt.Color(204, 204, 204));
        jLabelInicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/Icons/home.png"))); // NOI18N
        jLabelInicio.setText("Inicio");
        jLabelInicio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelInicio.setIconTextGap(15);
        add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 50));

        jLabelUsers.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelUsers.setForeground(new java.awt.Color(204, 204, 204));
        jLabelUsers.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/Icons/client.png"))); // NOI18N
        jLabelUsers.setText("Usuarios");
        jLabelUsers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabelUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUsers.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelUsers.setIconTextGap(15);
        add(jLabelUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, 50));

        jButton1.setBackground(new java.awt.Color(44, 62, 80));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/Icons/info.png"))); // NOI18N
        jButton1.setText("Información");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 230, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JLabel jLabelBuses;
    public static javax.swing.JLabel jLabelHome;
    public static javax.swing.JLabel jLabelInformation;
    public static javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelNombreUsuario;
    public static javax.swing.JLabel jLabelProgramming;
    public static javax.swing.JLabel jLabelReport;
    public static javax.swing.JLabel jLabelTicket;
    public static javax.swing.JLabel jLabelUsers;
    // End of variables declaration//GEN-END:variables
}
