/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

import javax.swing.JFrame;

import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import Conectar.*;
import Pagos.TipoPago;
import Users.*;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.Time;

import javax.swing.JOptionPane;

/**
 *
 * @author Henry
 */
public class Vender extends javax.swing.JFrame implements Fecha.Listener {

    private DateTimeFormatter horaFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
    private DateTimeFormatter fechaFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private DateTimeFormatter formatterSalida = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    private Fecha hora;
    private int numeroAsiento; //-------TEMPORAL
    /**
     * Creates new form Pasajes
     */
    public Vender(int numeroAsiento) {
        this.numeroAsiento = numeroAsiento;
        initComponents();

    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonSell = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextHora = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jTextDNI = new javax.swing.JTextField();
        jTextDireccion = new javax.swing.JTextField();
        jTextCelular = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ID_bus = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextOrigen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Destino = new javax.swing.JComboBox<>();
        n_asiento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Pago = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        Hora_salida = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        // para mostar la hora y fecha actual
        jPanel1.add(jTextHora, BorderLayout.WEST);
        jPanel1.add(jTextFecha, BorderLayout.CENTER);
        
        hora = new Fecha();
        hora.addListener(this);
        LocalTime horaActual = LocalTime.now();
        actualizarHora(horaActual);
        
        LocalDate fechaActual = LocalDate.now();
        updateFecha(fechaActual);

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        buttonSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venderP.png"))); // NOI18N
        buttonSell.setText("Vender");
        buttonSell.setContentAreaFilled(false);
        buttonSell.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonSell.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venderP.png"))); // NOI18N
        buttonSell.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venderG.png"))); // NOI18N
        buttonSell.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSellActionPerformed(evt);
            }
        });

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarP.png"))); // NOI18N
        Cancel.setText("Cancelar");
        Cancel.setContentAreaFilled(false);
        Cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cancel.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarP.png"))); // NOI18N
        Cancel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarG.png"))); // NOI18N
        Cancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Hora: ");

        jTextHora.setText("");

        jLabel2.setText("Fecha: ");

        jTextFecha.setText("");

        jLabel3.setText("DATOS DEL PASAJERO");

        jLabel4.setText("Nombres: ");

        jLabel5.setText("Apellidos:");

        jLabel6.setText("DNI:");

        jLabel7.setText("Direccion:");

        jLabel8.setText("Celular:");

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jLabel9.setText("ID de Vehiculo:");

        ID_bus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehiculo N:1", "Vehiculo N:2", "Vehiculo N:3"}));

        jLabel10.setText("Origen: ");

        jTextOrigen.setText("Abancay");

        jLabel11.setText("Destino:");

        Destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chalhuanca", "Anduahuaylas", "Grau","Cusco" }));

        n_asiento.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        n_asiento.setText(numeroAsiento+"");

        jLabel13.setText("Hora salida: ");

        Pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Movil" }));

        jLabel14.setText("Precio:");

        Hora_salida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00:00","8:00:00","9:00:00","10:00:00","11:00:00","12:00:00","13:00:00","14:00:00","15:00:00" }));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bus.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextHora, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(n_asiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(buttonSell)
                                .addGap(77, 77, 77)
                                .addComponent(Cancel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(89, 89, 89)
                                                        .addComponent(jLabel9))
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel14))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(39, 39, 39)
                                                        .addComponent(Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(Hora_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(Pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jTextOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(39, 39, 39)
                                                        .addComponent(ID_bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(n_asiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(ID_bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(Hora_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(Pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSell)
                    .addComponent(Cancel))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setTitle("VENDER PASAJE");
        pack();
        setLocationRelativeTo(null);

        // Confirmacion para cerrar la ventana
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int confirm = JOptionPane.showOptionDialog(
                        Vender.this,
                        "Estás seguro de que deseas cerrar la ventana?",
                        "Confirmar salida", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, null, null);

                if (confirm == JOptionPane.YES_OPTION) {
                    // Detener el hilo de la instancia de Fecha
                    hora.detener();
                    // Cerrar la ventana
                    Vender.this.dispose();
                    // FALTA CORREGIR
                }
            }
        });
   
        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update(LocalTime hora) {
        actualizarHora(hora);
        updateFecha(LocalDate.now());
    }
    private void actualizarHora(LocalTime hora) {
        String horaFormateada = hora.format(horaFormatter);
        jTextHora.setText(horaFormateada);
    }
    private void updateFecha(LocalDate fecha) {
        String fechaFormateada = fecha.format(fechaFormatter);
        jTextFecha.setText(fechaFormateada);
    }



    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void buttonSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSellActionPerformed
        String celular = jTextCelular.getText();
        String dni = jTextDNI.getText();

        int opcion = JOptionPane.showConfirmDialog(null, "¿Cofirmar venta?", "Confirmarmación", JOptionPane.YES_NO_OPTION);
        // para tener la tabla vehico se guarda previamente en la DB
        if ((opcion == JOptionPane.YES_OPTION) && (celular.length() == 9 && dni.length() == 8 )) {

            Vehiculo.numeroVehiculo((String) ID_bus.getSelectedItem());
            Actualizar.ulitmasID();

            tableCLIENTE();
            tableTIPO_PAGO();
            tableVIAJE();
            tableVENTA();
            tableBOLETA();
            // Detener el hilo de la instancia de Fecha
            hora.detener();
            // Cerrar la ventana
            this.dispose();

        } else {
            setVisible(true);
            JOptionPane.showMessageDialog(null, "Datos incorrectos verifique su DNI y celular");
            // Código para cancelar la acción
        }
   
    }//GEN-LAST:event_buttonSellActionPerformed


    private void CancelActionPerformed(java.awt.event.ActionEvent evt){
        // Detener el hilo de la instancia de Fecha
        hora.detener();
        // Cerrar la ventana
        this.dispose();
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JComboBox<String> Destino;
    private javax.swing.JComboBox<String> Hora_salida;
    private javax.swing.JComboBox<String> ID_bus;
    private javax.swing.JComboBox<String> Pago;
    private javax.swing.JButton buttonSell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextCelular;
    private javax.swing.JTextField jTextDNI;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextHora;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextOrigen;
    private javax.swing.JTextField n_asiento;
    // End of variables declaration//GEN-END:variables


    public void tableCLIENTE(){
        Connection connection = null;
        PreparedStatement stmt = null;
        String query;
        try {
            connection = Conexion.getConnection();
            query = "INSERT INTO CLIENTE (cliente_ID, cliente_DNI, cliente_nombre, cliente_apellido, cliente_direccion, cliente_celular) VALUES(?,?,?,?,?,?)";
            stmt = connection.prepareStatement(query);

            stmt.setString(1,Tablas.ClienteID);
            stmt.setInt(2,Integer.parseInt(jTextDNI.getText()));
            stmt.setString(3,jTextNombre.getText());
            stmt.setString(4,jTextApellido.getText());
            stmt.setString(5,jTextDireccion.getText());
            stmt.setInt(6,Integer.parseInt(jTextCelular.getText()));

            print.comprobarGuardado(stmt.executeUpdate(),"cliente");

            stmt.close();
            connection.close(); // cerramos la conexion
        } catch (Exception e) {
            System.out.println(e);
        }
    };

    public void tableTIPO_PAGO(){
        Connection connection = null;
        PreparedStatement stmt = null;
        String query;

        TipoPago.pagoEfectico((String) Pago.getSelectedItem());
        try {
            connection = Conexion.getConnection();
            query = "INSERT INTO TIPO_PAGO (pago_ID, pago_efectivo, pago_tarjeta, pago_movil) VALUES(?,?,?,?)";
            stmt = connection.prepareStatement(query);

            stmt.setString(1,Tablas.PagoID);
            stmt.setBigDecimal(2, TipoPago.efectivo);
            stmt.setBigDecimal(3, TipoPago.tarjeta);
            stmt.setBigDecimal(4, TipoPago.movil);
            
            print.comprobarGuardado(stmt.executeUpdate(),"tipo pago");

            stmt.close();
            connection.close(); // cerramos la conexion
        } catch (Exception e) {
            System.out.println(e);
        }
    };

    public void tableVENTA(){
        Connection connection = null;
        PreparedStatement stmt = null;
        String query;
        try {
            connection = Conexion.getConnection();
            query = "INSERT INTO VENTA (venta_ID, venta_destino, venta_fecha, usuario_ID, cliente_ID, pago_ID, vehiculo_placa) VALUES(?,?,?,?,?,?,?)";
            stmt = connection.prepareStatement(query);

            stmt.setString(1,Tablas.VentaID);
            stmt.setString(2,(String) Destino.getSelectedItem());
            stmt.setDate(3,Date.valueOf(revertirFecha(jTextFecha.getText()))); // corregir
            stmt.setString(4,Usuario.usuarioID);
            stmt.setString(5,Tablas.ClienteID);
            stmt.setString(6,Tablas.PagoID);
            stmt.setString(7,Tablas.VehiculoID);
           

            print.comprobarGuardado(stmt.executeUpdate(),"venta");
            stmt.close();
            connection.close(); // cerramos la conexion
        } catch (Exception e) { System.out.println(e); }
    };
    

    public void tableVIAJE(){
        Connection connection = null;
        PreparedStatement stmt = null;
        String query;
        Object hora_salida = Hora_salida.getSelectedItem();//--->
        try {
            connection = Conexion.getConnection();
            query = "INSERT INTO VIAJE (viaje_ID, viaje_fecha, viaje_hora, viaje_destino, vehiculo_placa) VALUES(?,?,?,?,?)";
            stmt = connection.prepareStatement(query);

            stmt.setString(1,Tablas.ViajeID);
            stmt.setDate(2, Date.valueOf(revertirFecha(jTextFecha.getText())));// corrregir
            stmt.setTime(3, Time.valueOf(hora_salida.toString())); //---->
            stmt.setString(4,(String) Destino.getSelectedItem());
            stmt.setString(5, Tablas.VehiculoID);

            print.comprobarGuardado(stmt.executeUpdate(),"viaje");
            stmt.close();
            connection.close(); // cerramos la conexion
        } catch (Exception e) { System.out.println(e); }

    };


    public void tableBOLETA(){
        Connection connection = null;
        PreparedStatement stmt = null;
        String query;
        try {
            connection = Conexion.getConnection();
            query = "INSERT INTO BOLETA (boleta_ID, boleta_precio, boleta_asiento, venta_ID, viaje_ID) VALUES(?,?,?,?,?)";
            stmt = connection.prepareStatement(query);

            stmt.setString(1,Tablas.BoletaID);
            stmt.setBigDecimal(2, TipoPago.efectivo);
            stmt.setInt(3, numeroAsiento);
            stmt.setString(4,Tablas.VentaID);
            stmt.setString(5,Tablas.ViajeID);

            print.comprobarGuardado(stmt.executeUpdate(),"boleta");
            stmt.close();
            connection.close(); // cerramos la conexion
        } catch (Exception e) { System.out.println(e); }
    };

    private String revertirFecha(String d){

        d.replace("/", "-"); 

        LocalDate fecha = LocalDate.parse(d, fechaFormatter);
        String fechaFormateada = fecha.format(formatterSalida);

        return fechaFormateada;
    }

}
