package View.Tickets;


public class JInternalTicket extends javax.swing.JInternalFrame {

    private JPanelSaleTicket sale;
    
    
    public JInternalTicket() {
        initComponents();
        this.sale = new JPanelSaleTicket();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Barra = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Venta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1320, 738));
        setPreferredSize(new java.awt.Dimension(1320, 738));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Fondo.setMinimumSize(new java.awt.Dimension(1320, 738));
        jPanel_Fondo.setPreferredSize(new java.awt.Dimension(1320, 738));
        jPanel_Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Venta de Pasajes");
        jPanel_Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 190, 50));

        jPanel_Barra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel_Barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Anular Boletos");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Barra.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 150, 40));

        jLabel_Venta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_Venta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Venta.setText("Venta Boletos");
        jLabel_Venta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_Venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_VentaMouseClicked(evt);
            }
        });
        jPanel_Barra.add(jLabel_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Actualizar Boleto");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_Barra.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 150, 40));

        jPanel_Fondo.add(jPanel_Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 820, 40));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel_Fondo.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("BUS :");
        jPanel_Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 60, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel_Fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, 350, 510));

        getContentPane().add(jPanel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_VentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_VentaMouseClicked
        // TODO add your handling code here:
        panelVenta();
    }//GEN-LAST:event_jLabel_VentaMouseClicked

    private void panelVenta(){
        //sale.setLocation(50,110);
        sale.setVisible(true);
        jPanel_Fondo.add(sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Venta;
    private javax.swing.JPanel jPanel_Barra;
    private javax.swing.JPanel jPanel_Fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
